### ISSUE TITLE
Extended app metadata model

### ISSUE THREAD

**Issue by OxygenCobalt** [accrescent/parcelo#209]
Related to https://github.com/accrescent/meta/issues/21 https://github.com/accrescent/meta/issues/16 https://github.com/accrescent/meta/issues/14 https://github.com/accrescent/meta/issues/12 https://github.com/accrescent/meta/issues/4, the backend should have an MVP data model roughly modeled by fastlane that serves the following:

- Changelog
- Short & Long Description
- Screenshots

Beyond MVP, these non-fastlane attributes should also be available:
- Organization/Author
- Tags/Categories
- External Links

**Comment by lberrymage** [comment]
Closing in favor of the above individual issues
