### ISSUE TITLE
Create Docker setup 

### ISSUE THREAD

**Issue by OxygenCobalt** [accrescent/parcelo#449]
Would allow us to automate deployment and make it easier for external contributors and deployers of parcelo to set up the server.

**Comment by lberrymage** [comment]
Completed in https://github.com/accrescent/parcelo/commit/17eb4fe178a8177a4f64990ff8910207ae3e7f93 for a production Docker setup. We plan to publish official images in the near future.

I've created https://github.com/accrescent/parcelo/issues/689 for a separate development setup.
