### ISSUE TITLE
Accrescent Large APP/OBB Storage Release Solution

### ISSUE THREAD

**Issue by atlantis451** [accrescent/parcelo#627]
### Accrescent server
1. Developers Upload APK/OBB or submit it to Accrescent Developer Platform via `.github/workflows`.
2. Storage Signing certificate hash is used to verify the integrity of the apk/obb file.
3. Accrescent synchronizes the app to a repository https://github.com/accrescent/Allapps 

### Accrescent client
1. Add cdn repository  https://cdn.jsdelivr.net/gh/accrescent/Allapps/
> Users don't download via accrescent.app, but via cdn for the repository `accrescent/Allapps` APP/OBB.
Can be any cdn
2. Add Verification Link  Signing certificate hash
> Installation after verifying the hash of the downloaded APP/OBB signing certificate

### Additional Context
[Git Large File Storage (LFS)](https://git-lfs.com/) can upload a 2GB single APP/OBB to a github gitlab repository etc.

**Comment by lberrymage** [comment]
What exactly are you proposing? We already have a publishing workflow.
